networks:
  ordini_network:
    driver: bridge

volumes:
  ordini_product_db_data:

services:
  postgres_db_product:
    image: postgres:latest
    container_name: ordini_postgres_product
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    command: -p 5433
    expose:
      - "5433"
    ports:
      - "5433:5433"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -h localhost -p 5433 -U ${DATASOURCE_USERNAME} -d ${DATASOURCE_DATABASE}",
      ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - ordini_network
    volumes:
      - ordini_product_db_data:/var/lib/postgresql/data

  app:
    container_name: ordini_product
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      #      JAVA_OPTS: "-Xms512m -Xmx1024m"
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
    depends_on:
      postgres_db_product:
        condition: service_healthy
    networks:
      - ordini_network
